### PR TITLE
IRON-1233 Implement extract alpha data.

### PR DESCRIPTION
**Pull request by mee-ironsoftware**
### Description
Implement `ExtractAlphaData()` which will return array of alpha channel in byte. This function supported only image which in 32 bpp format.

Also add tag NuGet version to deployment pipeline when run successfully.

```csharp
var bitmap = new AnyBitmap("32_bit_transparent.png");
byte[] result = bitmap.ExtractAlphaData();
```

Fixes [#IRON-1233](https://ironsoftware.atlassian.net/browse/IRON-1233)

### Type of change
Please select the relevant option by placing an 'x' inside the brackets, like this: [x].

- [ ] 🐛 Bug fix (non-breaking change which fixes an issue)
- [X] ✨ New feature (non-breaking change which adds functionality)
- [ ] 💥 Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] 🏗️ Internal/structural update (non-breaking change that improves code quality, organization, or performance)
- [ ] 📚 This change requires a documentation update
- [ ] 🚀 DevOps build chain modification for release
- [ ] 🤖 DevOps build chain modification for CI

### How Has This Been Tested?
Add 2 tests which are return correct result and throw exception.

### Checklist:
Please run through the checklist as much as possible and mark the items completed by placing an 'x' inside the brackets, like this: [x].

- [ ] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] I have successfully run all unit tests on Windows
- [X] I have successfully run all unit tests on Linux

### CODE REVIEW

**Comment by artem-iron** [comment]
Is alpha 0 means that the pixel is transparent? Maybe in the unit test, check also a couple of pixels that don't have 0?

**Comment by artem-iron** [comment]
Just to be safe.

**Review by artem-iron — APPROVED** [review]
LGTM 🚀

**Comment by mee-ironsoftware** [comment]
> Is alpha 0 means that the pixel is transparent? Maybe in the unit test, check also a couple of pixels that don't have 0?

@artem-iron 
Thanks, good point. 💪 
I modified test to check various values from result.

**Pull request merged**
